development:
  default: &default
  adapter: postgresql
  username: postgres
  password: "ols13"
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer_development

test:
  default: &default
  adapter: postgresql
  username: postgres
  password: "ols13"
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer_test

production:
  default: &default
  adapter: postgresql
  username: postgres
  password: "ols13"
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer_production

development:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer development

test:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer test

production:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer production
