development:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer development

test:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer test

production:
  adapter: postgresql
  username: Jason
  password: admin
  host: localhost
  port: 5432
  pool: 5
  database: spec_writer production
